#+TITLE: Solutions For The Political Division In FOSS
#+AUTHOR: Derek Taylor

* SOLUTIONS FOR THE POLITICAL DIVISION IN FOSS
+ VERSION: 1.0
+ DATE: April 13, 2024
+ AUTHOR: Derek Taylor (Edited by Bhargav Ekbote)

This is written in an attempt to help free and open source software (FOSS) project leaders and community managers in curbing the increasing political division within our communities as well as avoiding some potential pitfalls.

** 1. Be Respectful To All
Be respectful to all--or at least attempt to be respectful.  This includes calling people by their preferred names, titles and pronouns.  If someone wants to be called a Martian, then call them a Martian.  If someone else wants to be called Dragon Slayer, then call them Dragon Slayer.  If you begin an interaction by purposely mispronouncing their name or misrepresenting their gender identity, then you are stating up front that you have no respect for that person, and you have destroyed any chance of having a good working relationship going forward.

** 2. Beware Of Chat And Messaging Platforms
FOSS projects should =NOT= have communities on chat and messaging platforms such as Discord, Matrix, IRC, Reddit, etc. unless there is an actual need for the project to have a presence on those platforms, and only if the project can moderate the activity on those platforms appropriately.  Official chat rooms and forums are perceived as an extension of your project, so any bad actors on these platforms will reflect poorly on the project.  For all but the largest projects, having a presence on these platforms is not worth the hassle.

** 3. Don't Be More Active Than You Need To Be
Do =NOT= actively participate in FOSS projects/communities unless there is a good reason for you to be there.  Do not join every project that you can find.  Why would you want to be involved in so many communities?  You cannot possibly contribute in a meaningful way to all of them.  Are you there to stroke your ego?  Are there to stir up drama?  If you are not contributing code, artwork, translations, documentation, etc. then you are probably there searching for "excitement."  If so, look elsewhere.

** 4. Broad Messages Have Greater Appeal
Broad messages appeal to the most people.  FOSS projects should =NEVER= make their messaging so narrow that it severely limits the number of people that can actively participate in the project.  "Candy is good," is a message that most people can get behind.  "Chocolate-covered insects are good," is not nearly as appealing to most people.  Another example: if your project's goal is mainly to spread awareness of FOSS, it would be highly detrimental to that goal to also attach your project to a variety of socio-political issues.

Use moderated, archival-friendly platforms (e.g., a LetsChat instance or Matrix) with clear rules. Avoid real-time chat for complex discussions.
